.TH .PARSE_SPECTRUM4 1 2025-Jul "" "Parse the ms2 predicted spectrum data"
.SH NAME
.parse_spectrum4 \- .parse_spectrum4(lines)
.SH SYNOPSIS
\fI.parse_spectrum4(lines)\fR
.SH OPTIONS
.PP
\fBlines\fB \fR\- . 
.PP
.SH VALUE
.PP
ms2 spectrum data in multiple level of the collision energy
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..parse_spectrum4 at cfmid4.R:line 57
.PP
.SH COPYRIGHT
Copyright © xieguigang@metabolomics.ac.cn, MIT Licensed 2025
