.TH .PARSE_ANNOTATION4 1 2025-Jul "" "Parse the ms2 spectrum fragment annotation information"
.SH NAME
.parse_annotation4 \- .parse_annotation4(lines)
.SH SYNOPSIS
\fI.parse_annotation4(lines)\fR
.SH OPTIONS
.PP
\fBlines\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..parse_annotation4 at cfmid4.R:line 42
.PP
.SH COPYRIGHT
Copyright © xieguigang@metabolomics.ac.cn, MIT Licensed 2025
