.TH .PARSE_METADATA4 1 2025-Jul "" "Parse the annotation metadata"
.SH NAME
.parse_metadata4 \- .parse_metadata4(lines)
.SH SYNOPSIS
\fI.parse_metadata4(lines)\fR
.SH OPTIONS
.PP
\fBlines\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..parse_metadata4 at cfmid4.R:line 69
.PP
.SH COPYRIGHT
Copyright © xieguigang@metabolomics.ac.cn, MIT Licensed 2025
