.TH __GCMS_ANNOTATION 1 2025-Jan "" "run single gcms annotation"
.SH NAME
__gcms_annotation \- __gcms_annotation(rawfile, ions, libname, libs, argv)
.SH SYNOPSIS
\fI__gcms_annotation(rawfile, ions, libname, libs, argv)\fR
.SH OPTIONS
.PP
\fBrawfile\fB \fR\- . 
.PP
.PP
\fBions\fB \fR\- . 
.PP
.PP
\fBlibname\fB \fR\- . 
.PP
.PP
\fBlibs\fB \fR\- . 
.PP
.PP
\fBargv\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__gcms_annotation at gcms_tof.R:line 95
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
