.TH __GCMS_ANNOTATION 1 2024-Dec "" "__gcms_annotation"
.SH NAME
__gcms_annotation \- __gcms_annotation(rawfile, peaktable, argv)
.SH SYNOPSIS
\fI__gcms_annotation(rawfile, peaktable, argv)\fR
.SH OPTIONS
.PP
\fBrawfile\fB \fR\- . 
.PP
.PP
\fBpeaktable\fB \fR\- . 
.PP
.PP
\fBargv\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__gcms_annotation at gcms_tof.R:line 70
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
