.TH __GCMS_FILE_ANNOTATION 1 2025-Feb "" "__gcms_file_annotation"
.SH NAME
__gcms_file_annotation \- __gcms_file_annotation(filepath, peaktable, work.pars)
.SH SYNOPSIS
\fI__gcms_file_annotation(filepath, peaktable, work.pars)\fR
.SH OPTIONS
.PP
\fBfilepath\fB \fR\- . 
.PP
.PP
\fBpeaktable\fB \fR\- . 
.PP
.PP
\fBwork.pars\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__gcms_file_annotation at gcms_tof.R:line 49
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
