.TH __LOAD_GCMS_LIBS 1 2024-Dec "" "__load_gcms_libs"
.SH NAME
__load_gcms_libs \- __load_gcms_libs(
    <i>argv</i> = 'list'('libfiles' = NULL, 'libtype' = [1, -1]))
.SH SYNOPSIS
\fI__load_gcms_libs(
    <i>argv</i> = 'list'('libfiles' = NULL, 'libtype' = [1, -1]))\fR
.SH OPTIONS
.PP
\fBargv\fB \fR\- 'list'('libfiles' = NULL, 'libtype' = [1, -1]). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__load_gcms_libs at gcms.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
