.TH __LOAD_LCMS_LIBS 1 2025-Jul "" "load lcms library database"
.SH NAME
__load_lcms_libs \- __load_lcms_libs(
    <i>argv</i> = 'list'('libfiles' = NULL, 'libtype' = [1, -1], 'waters' = FALSE),
    <i>load.spectrum</i> = <span style='color: blue !important;'>TRUE</span>,
    <i>map.name</i> = <span style='color: blue !important;'>NULL</span>,
    <i>target.idset</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fI__load_lcms_libs(
    <i>argv</i> = 'list'('libfiles' = NULL, 'libtype' = [1, -1], 'waters' = FALSE),
    <i>load.spectrum</i> = <span style='color: blue !important;'>TRUE</span>,
    <i>map.name</i> = <span style='color: blue !important;'>NULL</span>,
    <i>target.idset</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBargv\fB \fR\- 'list'('libfiles' = NULL, 'libtype' = [1, -1], 'waters' = FALSE). 
.PP
.PP
\fBload.spectrum\fB \fR\- TRUE. 
.PP
.PP
\fBmap.name\fB \fR\- NULL. 
.PP
.PP
\fBtarget.idset\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__load_lcms_libs at lcms.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
