.TH __LOAD_LCMS_LIBS 1 2025-Jun "" "load lcms library database"
.SH NAME
__load_lcms_libs \- __load_lcms_libs(
    <i>argv</i> = 'list'('libfiles' = NULL, 'libtype' = [1, -1], 'waters' = FALSE))
.SH SYNOPSIS
\fI__load_lcms_libs(
    <i>argv</i> = 'list'('libfiles' = NULL, 'libtype' = [1, -1], 'waters' = FALSE))\fR
.SH OPTIONS
.PP
\fBargv\fB \fR\- 'list'('libfiles' = NULL, 'libtype' = [1, -1], 'waters' = FALSE). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__load_lcms_libs at lcms.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
