.TH __PEAK_ALIGNMENT 1 2025-Jun "" "__peak_alignment"
.SH NAME
__peak_alignment \- __peak_alignment(xcms.out,
    <i>max.rtwin</i> = <span style='color: green;'>15</span>,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fI__peak_alignment(xcms.out,
    <i>max.rtwin</i> = <span style='color: green;'>15</span>,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBxcms.out\fB \fR\- . 
.PP
.PP
\fBmax.rtwin\fB \fR\- 15. 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__peak_alignment at deconv_peaks.R:line 49
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
