.TH BUILD_MONA_LCMS 1 2025-Feb "" "build lcms reference library for MoNA LC-MS dataset"
.SH NAME
build_mona_lcms \- build_mona_lcms(repo,
    <i>libdir</i> = <span style='color: brown;'><strong>'./MoNA'</strong></span>)
.SH SYNOPSIS
\fIbuild_mona_lcms(repo,
    <i>libdir</i> = <span style='color: brown;'><strong>'./MoNA'</strong></span>)\fR
.SH OPTIONS
.PP
\fBrepo\fB \fR\- . a local directory path that contains multiple msp data files that could be download from the MoNA database.
.PP
.PP
\fBlibdir\fB \fR\- './MoNA'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.build_mona_lcms at build_mona_lcms.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
