.TH BUILDCFMIDDB 1 2025-May "" "buildCfmidDb"
.SH NAME
buildCfmidDb \- buildCfmidDb(cfmid, libfile)
.SH SYNOPSIS
\fIbuildCfmidDb(cfmid, libfile)\fR
.SH OPTIONS
.PP
\fBcfmid\fB \fR\- . 
.PP
.PP
\fBlibfile\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.buildCfmidDb at buildCfmidDb.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
