.TH CALL_METADNA 1 2025-Apr "" "run metadna algorithm"
.SH NAME
call_metadna \- call_metadna(peaks.ms2,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>ms1ppm</i> = <span style='color: green;'>15</span>,
    <i>output</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIcall_metadna(peaks.ms2,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>ms1ppm</i> = <span style='color: green;'>15</span>,
    <i>output</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBpeaks.ms2\fB \fR\- . 
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. 
.PP
.PP
\fBms1ppm\fB \fR\- 15. 
.PP
.PP
\fBoutput\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.call_metadna at metadna.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
