.TH CALL_LIBRARYSEARCH 1 2025-Jan "" "call_librarysearch"
.SH NAME
call_librarysearch \- call_librarysearch(peaks.ms2,
    <i>libfiles</i> = <span style='color: blue !important;'>NULL</span>,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>output</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIcall_librarysearch(peaks.ms2,
    <i>libfiles</i> = <span style='color: blue !important;'>NULL</span>,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>output</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBpeaks.ms2\fB \fR\- . 
.PP
.PP
\fBlibfiles\fB \fR\- NULL. 
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. 
.PP
.PP
\fBoutput\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.call_librarysearch at librarySearch.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
