.TH DASY_TASK 1 2025-Jan "" "A annotation task for a single rawdata file"
.SH NAME
dasy_task \- dasy_task(file, args)
.SH SYNOPSIS
\fIdasy_task(file, args)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . the file path character vector of the rawdata file, should be in file format of mzkit supported mzXML/mzML/mzPack.
.PP
.PP
\fBargs\fB \fR\- . the workflow arguments for run this annotation.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.dasy_task at parallel.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
