.TH DASY_TASK 1 2025-Jul "" "A annotation task for a single rawdata file"
.SH NAME
dasy_task \- dasy_task(file,
    <i>args</i> = 'list'('export_dir' = './', 'peakfile' = './peaksdata.csv', 'library_dir' = NULL, 'ms1_da' = 0.1, 'rt_winsize' = 10, 'libtype' = 1, 'ms1ppm' = 15, 'waters' = FALSE, 'metadna' = TRUE))
.SH SYNOPSIS
\fIdasy_task(file,
    <i>args</i> = 'list'('export_dir' = './', 'peakfile' = './peaksdata.csv', 'library_dir' = NULL, 'ms1_da' = 0.1, 'rt_winsize' = 10, 'libtype' = 1, 'ms1ppm' = 15, 'waters' = FALSE, 'metadna' = TRUE))\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . 
.PP
.PP
\fBargs\fB \fR\- 'list'('export_dir' = './', 'peakfile' = './peaksdata.csv', 'library_dir' = NULL, 'ms1_da' = 0.1, 'rt_winsize' = 10, 'libtype' = 1, 'ms1ppm' = 15, 'waters' = FALSE, 'metadna' = TRUE). the workflow arguments for run this annotation.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.dasy_task at parallel.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang@metabolomics.ac.cn, MIT Licensed 2025
