.TH DASY_TASK 1 2024-Jun "" "dasy_task"
.SH NAME
dasy_task \- dasy_task(file, args)
.SH SYNOPSIS
\fIdasy_task(file, args)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . 
.PP
.PP
\fBargs\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.dasy_task at parallel.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
