.TH DECONV_PEAKS 1 2025-Jun "" "method for export peakstable for both lcms and gcms"
.SH NAME
deconv_peaks \- deconv_peaks(rawfiles,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>max.rtwin</i> = <span style='color: green;'>15</span>,
    <i>docker</i> = <span style='color: blue !important;'>NULL</span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>,
    <i>call.xcms</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIdeconv_peaks(rawfiles,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>max.rtwin</i> = <span style='color: green;'>15</span>,
    <i>docker</i> = <span style='color: blue !important;'>NULL</span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>,
    <i>call.xcms</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBrawfiles\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.PP
\fBmax.rtwin\fB \fR\- 15. 
.PP
.PP
\fBdocker\fB \fR\- NULL. 
.PP
.PP
\fBn.threads\fB \fR\- 8. 
.PP
.PP
\fBcall.xcms\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.deconv_peaks at deconv_peaks.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
