.TH EXPORT_REPORT 1 2025-Feb "" "export report table and spectrum alignment mirror plot"
.SH NAME
export_report \- export_report(files,
    <i>export.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIexport_report(files,
    <i>export.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBfiles\fB \fR\- . 
.PP
.PP
\fBexport.dir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.export_report at report.R:line 4
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
