.TH GCMS_MONA_MSP 1 2025-Jun "" "load gcms library in mona msp file format"
.SH NAME
gcms_mona_msp \- gcms_mona_msp(mspfile,
    <i>libtype</i> = [<span style='color: green;'>-1</span>])
.SH SYNOPSIS
\fIgcms_mona_msp(mspfile,
    <i>libtype</i> = [<span style='color: green;'>-1</span>])\fR
.SH OPTIONS
.PP
\fBmspfile\fB \fR\- . 
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. 
.PP
.SH VALUE
.PP
a cluster tree of the reference spectrum for make spectrum similarity search.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.gcms_mona_msp at mona.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
