.TH GCMS_MONA_MSP 1 2024-Dec "" "load gcms library in mona msp file format"
.SH NAME
gcms_mona_msp \- gcms_mona_msp(mspfile)
.SH SYNOPSIS
\fIgcms_mona_msp(mspfile)\fR
.SH OPTIONS
.PP
\fBmspfile\fB \fR\- . the filepath to the msp library file
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.gcms_mona_msp at mona.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
