.TH GCMS_TOF_ANNOTATION 1 2024-Dec "" "Run untargetted annotation for gc-ms"
.SH NAME
gcms_tof_annotation \- gcms_tof_annotation(rawdir, peaktable,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>ppm.cutoff</i> = <span style='color: green;'>20</span>,
    <i>lib.files</i> = <span style='color: blue !important;'>NULL</span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIgcms_tof_annotation(rawdir, peaktable,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>ppm.cutoff</i> = <span style='color: green;'>20</span>,
    <i>lib.files</i> = <span style='color: blue !important;'>NULL</span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBrawdir\fB \fR\- . 
.PP
.PP
\fBpeaktable\fB \fR\- . 
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.PP
\fBppm.cutoff\fB \fR\- 20. 
.PP
.PP
\fBlib.files\fB \fR\- NULL. 
.PP
.PP
\fBn.threads\fB \fR\- 8. 
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.gcms_tof_annotation at gcms_tof.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
