.TH GET_ADDUCTS 1 2025-Mar "" "precursor adducts provider for the workflow"
.SH NAME
get_adducts \- get_adducts(
    <i>ionMode</i> = [<span style='color: green;'>-1</span>])
.SH SYNOPSIS
\fIget_adducts(
    <i>ionMode</i> = [<span style='color: green;'>-1</span>])\fR
.SH OPTIONS
.PP
\fBionMode\fB \fR\- [1, -1]. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_adducts at precursors.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
