.TH MAKE_MSMS_PLOT 1 2025-May "" "plot visual of the spectrum alignment"
.SH NAME
make_msms_plot \- make_msms_plot(result,
    <i>visual.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fImake_msms_plot(result,
    <i>visual.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBresult\fB \fR\- . 
.PP
.PP
\fBvisual.dir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.make_msms_plot at report.R:line 32
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
