.TH MAKE_ANNOTATION 1 2024-Jun "" "Run metabolite annotation search"
.SH NAME
make_annotation \- make_annotation(files, peakfile,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>ms1ppm</i> = <span style='color: green;'>15</span>,
    <i>export.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fImake_annotation(files, peakfile,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>ms1ppm</i> = <span style='color: green;'>15</span>,
    <i>export.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBfiles\fB \fR\- . the file path to the rawdata files.
.PP
.PP
\fBpeakfile\fB \fR\- . the file path to the xcms peaktable file.
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. 
.PP
.PP
\fBms1ppm\fB \fR\- 15. 
.PP
.PP
\fBexport.dir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.make_annotation at main.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
