.TH MAKE_ANNOTATION 1 2025-Apr "" "Run metabolite annotation search"
.SH NAME
make_annotation \- make_annotation(files, peakfile,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>ms1ppm</i> = <span style='color: green;'>15</span>,
    <i>export.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>library.dir</i> = <span style='color: blue !important;'>NULL</span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>,
    <i>waters</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>metadna</i> = <span style='color: blue !important;'>TRUE</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fImake_annotation(files, peakfile,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>ms1ppm</i> = <span style='color: green;'>15</span>,
    <i>export.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>library.dir</i> = <span style='color: blue !important;'>NULL</span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>,
    <i>waters</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>metadna</i> = <span style='color: blue !important;'>TRUE</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBfiles\fB \fR\- . the file path to the rawdata files or a directory path that should contains the avaiable mass spectrum data files.
.PP
.PP
\fBpeakfile\fB \fR\- . the file path to the xcms peaktable file.
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. the ion polarity mode of the rawdata files, should be an integer vector of 1 for positive and -1 for negative raw data.
.PP
.PP
\fBms1ppm\fB \fR\- 15. 
.PP
.PP
\fBexport.dir\fB \fR\- './'. 
.PP
.PP
\fBlibrary.dir\fB \fR\- NULL. 
.PP
.PP
\fBn.threads\fB \fR\- 8. 
.PP
.PP
\fBwaters\fB \fR\- FALSE. 
.PP
.PP
\fBmetadna\fB \fR\- TRUE. 
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.SH DETAILS
.PP
the input raw data files could be in data formats of: 1. open source: mzXML, mzML 2. panomix mzkit format: mzPack, PeakMs2
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.make_annotation at main.R:line 17
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
