.TH METADNA 1 2024-Jun "" "metadna"
.SH NAME
metadna \- metadna(peaks.ms2,
    <i>libtype</i> = [<span style='color: green;'>-1</span>])
.SH SYNOPSIS
\fImetadna(peaks.ms2,
    <i>libtype</i> = [<span style='color: green;'>-1</span>])\fR
.SH OPTIONS
.PP
\fBpeaks.ms2\fB \fR\- . 
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.metadna at metadna.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
