.TH METADNA_REPORT 1 2025-Jul "" "metadna_report"
.SH NAME
metadna_report \- metadna_report(metadna.result, metadb, args)
.SH SYNOPSIS
\fImetadna_report(metadna.result, metadb, args)\fR
.SH OPTIONS
.PP
\fBmetadna.result\fB \fR\- . 
.PP
.PP
\fBmetadb\fB \fR\- . 
.PP
.PP
\fBargs\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.metadna_report at metadna_report.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang@metabolomics.ac.cn, MIT Licensed 2025
