.TH MS1_ANNO 1 2025-Apr "" "MS1 annotation of the peaks"
.SH NAME
ms1_anno \- ms1_anno(peaks,
    <i>ms1ppm</i> = <span style='color: green;'>10</span>,
    <i>libtype</i> = [<span style='color: green;'>-1</span>])
.SH SYNOPSIS
\fIms1_anno(peaks,
    <i>ms1ppm</i> = <span style='color: green;'>10</span>,
    <i>libtype</i> = [<span style='color: green;'>-1</span>])\fR
.SH OPTIONS
.PP
\fBpeaks\fB \fR\- . the mzkit peakSet object, ms1 peaks table.
.PP
.PP
\fBms1ppm\fB \fR\- 10. 
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.ms1_anno at ms1.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
