.TH OPEN_BIOCAD_LOCAL 1 2025-Feb "" "Open local annotation library file"
.SH NAME
open_biocad_local \- open_biocad_local()
.SH SYNOPSIS
\fIopen_biocad_local()\fR
.SH VALUE
.PP
IMetaDb
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.open_biocad_local at local_biocad.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
