.TH PARSEMS 1 2025-Jul "" "Parse the ms2 spectrum data"
.SH NAME
parseMS \- parseMS(block)
.SH SYNOPSIS
\fIparseMS(block)\fR
.SH OPTIONS
.PP
\fBblock\fB \fR\- . 
.PP
.SH VALUE
.PP
the parsed ms2 spectrum data in a dataframe object, contains two data fields: - mz: the ms2 fragment mz data - into: the ms2 fragment intensity data
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.parseMS at parseMS.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang@metabolomics.ac.cn, MIT Licensed 2025
