.TH PARSE_CFMID4_PREDICTS 1 2025-Jul "" "Parse the cfm-id 4.0 spectra predicts result"
.SH NAME
parse_cfmid4_predicts \- parse_cfmid4_predicts(str.output)
.SH SYNOPSIS
\fIparse_cfmid4_predicts(str.output)\fR
.SH OPTIONS
.PP
\fBstr.output\fB \fR\- . 
.PP
.SH DETAILS
.PP
PMass is the precursor mz of [M+H]+ or [M-H]-
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.parse_cfmid4_predicts at cfmid4.R:line 13
.PP
.SH COPYRIGHT
Copyright © xieguigang@metabolomics.ac.cn, MIT Licensed 2025
