.TH PEAK_ALIGNMENT 1 2025-Jan "" "make peak alignment of the metadna result with peaktable"
.SH NAME
peak_alignment \- peak_alignment(metadna, peaktable,
    <i>mzdiff</i> = <span style='color: green;'>0.01</span>,
    <i>rt.win</i> = <span style='color: green;'>15</span>)
.SH SYNOPSIS
\fIpeak_alignment(metadna, peaktable,
    <i>mzdiff</i> = <span style='color: green;'>0.01</span>,
    <i>rt.win</i> = <span style='color: green;'>15</span>)\fR
.SH OPTIONS
.PP
\fBmetadna\fB \fR\- . 
.PP
.PP
\fBpeaktable\fB \fR\- . 
.PP
.PP
\fBmzdiff\fB \fR\- 0.01. 
.PP
.PP
\fBrt.win\fB \fR\- 15. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.peak_alignment at metadna.R:line 44
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
