.TH READ_RAWFILE 1 2025-Apr "" "rawdata lc-ms file processor"
.SH NAME
read_rawfile \- read_rawfile(file,
    <i>cache.enable</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIread_rawfile(file,
    <i>cache.enable</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . the file path to the lc-ms rawdata file
.PP
.PP
\fBcache.enable\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.read_rawfile at rawfile.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
