.TH READ_RAWFILE 1 2024-Jun "" "read_rawfile"
.SH NAME
read_rawfile \- read_rawfile(files)
.SH SYNOPSIS
\fIread_rawfile(files)\fR
.SH OPTIONS
.PP
\fBfiles\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.read_rawfile at rawfile.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
