.TH RESOLVE_METADB 1 2025-Jul "" "resolve_metadb"
.SH NAME
resolve_metadb \- resolve_metadb(
    <i>libfiles</i> = <span style='color: blue !important;'>NULL</span>,
    <i>map.name</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIresolve_metadb(
    <i>libfiles</i> = <span style='color: blue !important;'>NULL</span>,
    <i>map.name</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBlibfiles\fB \fR\- NULL. 
.PP
.PP
\fBmap.name\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.resolve_metadb at librarySearch.R:line 32
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
