.TH RESOLVE_METADB 1 2025-Jun "" "resolve_metadb"
.SH NAME
resolve_metadb \- resolve_metadb(
    <i>libfiles</i> = <span style='color: blue !important;'>NULL</span>,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>waters</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIresolve_metadb(
    <i>libfiles</i> = <span style='color: blue !important;'>NULL</span>,
    <i>libtype</i> = [<span style='color: green;'>-1</span>],
    <i>waters</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBlibfiles\fB \fR\- NULL. 
.PP
.PP
\fBlibtype\fB \fR\- [1, -1]. 
.PP
.PP
\fBwaters\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.resolve_metadb at librarySearch.R:line 25
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
