.TH TABULAR 1 2024-Dec "" "common method for make the annotation tabular outputs"
.SH NAME
tabular \- tabular(result)
.SH SYNOPSIS
\fItabular(result)\fR
.SH OPTIONS
.PP
\fBresult\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.tabular at tabular.R:line 4
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
