.TH TABULAR 1 2025-Apr "" "A helper function for make list to tabular report"
.SH NAME
tabular \- tabular(list, keys)
.SH SYNOPSIS
\fItabular(list, keys)\fR
.SH OPTIONS
.PP
\fBlist\fB \fR\- . 
.PP
.PP
\fBkeys\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.tabular at tabular.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
