.TH TABULAR_ANNOTATION 1 2025-Jun "" "tabular_annotation"
.SH NAME
tabular_annotation \- tabular_annotation(result,
    <i>rt.shifts</i> = <span style='color: green;'>15</span>)
.SH SYNOPSIS
\fItabular_annotation(result,
    <i>rt.shifts</i> = <span style='color: green;'>15</span>)\fR
.SH OPTIONS
.PP
\fBresult\fB \fR\- . 
.PP
.PP
\fBrt.shifts\fB \fR\- 15. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.tabular_annotation at report.R:line 92
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
