.TH UNION_POSNEG 1 2025-Mar "" "make union of the pos+neg annotation outputs"
.SH NAME
union_posneg \- union_posneg(pos, neg)
.SH SYNOPSIS
\fIunion_posneg(pos, neg)\fR
.SH OPTIONS
.PP
\fBpos\fB \fR\- . 
.PP
.PP
\fBneg\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.union_posneg at union_posneg.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
