.TH XCMS_FINDPEAKS 1 2025-Jun "" "xcms_findPeaks"
.SH NAME
xcms_findPeaks \- xcms_findPeaks(raw.files,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>docker</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIxcms_findPeaks(raw.files,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>docker</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBraw.files\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.PP
\fBdocker\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.xcms_findPeaks at xcms.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
